# Generated by Django 5.0 on 2024-01-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
