# Generated by Django 5.0 on 2024-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('Confirm_Password', models.IntegerField()),
            ],
        ),
    ]
